spring:

  profiles:
    active: dev

  datasource:
    url: jdbc:h2:mem:dishoftheday
    driverClassName: org.h2.Driver
    username: sa
    password:
    platform: h2

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

logging:
  level:
    org:
      springframework:
        web: debug
        orm:
          jpa: debug
    resultsettable: info
    sqltiming: info
    sqlonly: fatal
    audit: fatal
    resultset: fatal
    connection: fatal