drop table if exists RESTAURANTS;

DROP SEQUENCE GLOBAL_SQL IF EXISTS;

CREATE SEQUENCE GLOBAL_SEQ START WITH 100000;

create table RESTAURANTS
(
	ID      INTEGER       DEFAULT GLOBAL_SEQ.nextval PRIMARY KEY,
	NAME    VARCHAR(100)  not null	unique,
	ADDRESS VARCHAR(255)  not null	unique,
	EMAIL   VARCHAR(255)  unique,
	CONSTRAINT C_NAME_ADDRESS UNIQUE (NAME, ADDRESS)
);



